services:
  - type: web
    name: pawcanvas-store
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: STRIPE_SECRET_KEY
        sync: false
      - key: STRIPE_PUBLISHABLE_KEY
        sync: false
      - key: PRINTIFY_API_TOKEN
        sync: false
      - key: PRINTIFY_SHOP_ID
        value: "27142928"
      - key: PORT
        value: "10000"
